# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/danielaramos/CLionProjects/chessboard

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/danielaramos/CLionProjects/chessboard

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielaramos/CLionProjects/chessboard/CMakeFiles /Users/danielaramos/CLionProjects/chessboard//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/danielaramos/CLionProjects/chessboard/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chessboard

# Build rule for target.
chessboard: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chessboard
.PHONY : chessboard

# fast build rule for target.
chessboard/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/build
.PHONY : chessboard/fast

board.o: board.c.o
.PHONY : board.o

# target to build an object file
board.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/board.c.o
.PHONY : board.c.o

board.i: board.c.i
.PHONY : board.i

# target to preprocess a source file
board.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/board.c.i
.PHONY : board.c.i

board.s: board.c.s
.PHONY : board.s

# target to generate assembly for a file
board.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/board.c.s
.PHONY : board.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/main.c.s
.PHONY : main.c.s

move.o: move.c.o
.PHONY : move.o

# target to build an object file
move.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/move.c.o
.PHONY : move.c.o

move.i: move.c.i
.PHONY : move.i

# target to preprocess a source file
move.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/move.c.i
.PHONY : move.c.i

move.s: move.c.s
.PHONY : move.s

# target to generate assembly for a file
move.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chessboard.dir/build.make CMakeFiles/chessboard.dir/move.c.s
.PHONY : move.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chessboard"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... move.o"
	@echo "... move.i"
	@echo "... move.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

